[package]
name = "rust_node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httparse = "1.9.5"
rusty_v8 = "0.32.1"
tokio = { version = "1.40.0", features = ["full"] }
url = "2.5.2"
futures = "0.3"